In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
from datetime import datetime
import pandas as pd
import time
import os

In [2]:
service = Service(executable_path='/Applications/Chdriver/chromedriver')
driver = webdriver.Chrome(service=service)

url = 'https://www.cricbuzz.com/cricket-series/2059/indian-premier-league-2009/matches'
driver.get(url)

match_urls = []
matches = driver.find_elements(By.CLASS_NAME, 'cb-series-matches')
for match in matches:
    link_element = match.find_element(By.CLASS_NAME, 'text-hvr-underline').get_attribute('href')
    link = link_element.replace("cricket-scores", "live-cricket-scorecard")
    match_urls.append(link)

batter_data = {
    'Match Date': [],
    'Venue': [],
    'Link': [],
    'Runs': [],
    'Balls': [],
    'Fours': [],
    'Sixes': [],
    'Strike Rate': [],
    'Team': [],
    'Season': []
}

bowler_data = {
    'Match Date': [],
    'Venue': [],
    'Link': [],
    'Overs': [],
    'Maiden': [],
    'Runs': [],
    'Wicket': [],
    'No Ball': [],
    'Wide': [],
    'Economy': [],
    'Team': [],
    'Season': []
}

for url in match_urls:
    driver.get(url)
    time.sleep(1)

    try:
        venue = driver.find_element(By.XPATH, '//*[@id="page-wrapper"]/div[4]/div[1]/div[2]/a[2]/span/span[2]/span')
        
        season_element = driver.find_element(By.XPATH, '//*[@id="page-wrapper"]/div[4]/div[1]/div[2]/a[1]/span')
        season_words = season_element.text.split()[3:]
        season = ' '.join(season_words)
        
        date = driver.find_element(By.CSS_SELECTOR, 'span.schedule-date')
        date_object = pd.to_datetime(date.text, format='%A, %B %d, %Y')
        
        batting1 = driver.find_element(By.XPATH, '//*[@id="innings_1"]/div[1]')
        batting2 = driver.find_element(By.XPATH, '//*[@id="innings_2"]/div[1]')
        
        xpath1 = '//*[@id="innings_1"]/div[1]/div[1]/span[1]'
        xpath2 = '//*[@id="innings_2"]/div[1]/div[1]/span[1]'
        for section, team_xpath in zip([batting1, batting2], [xpath1, xpath2]):
            team_element = section.find_element(By.XPATH, team_xpath)
            team_words = team_element.text.split(' ')[:-1]
            initials = [word[0] for word in team_words]
            team_name = ''.join(initials)
            
            batters = section.find_elements(By.CLASS_NAME, 'cb-scrd-itms')
            for batter in batters[:-3]:
                batter_data['Venue'].append(venue.text)                
                batter_data['Season'].append(season)
                batter_data['Match Date'].append(date_object.strftime('%Y-%m-%d'))

                name_link = batter.find_element(By.CLASS_NAME, 'cb-text-link').get_attribute('href')
                batter_data['Link'].append(name_link)
                                
                scores = batter.find_elements(By.CLASS_NAME, 'text-right')
                batter_data['Runs'].append(scores[0].text)
                batter_data['Balls'].append(scores[1].text)
                batter_data['Fours'].append(scores[2].text)
                batter_data['Sixes'].append(scores[3].text)
                batter_data['Strike Rate'].append(scores[4].text)
                batter_data['Team'].append(team_name)
            
        bowling1 = driver.find_element(By.XPATH, '//*[@id="innings_1"]/div[4]')
        bowling2 = driver.find_element(By.XPATH, '//*[@id="innings_2"]/div[4]')
        xpath1 = '//*[@id="innings_1"]/div[1]/div[1]/span[1]'
        xpath2 = '//*[@id="innings_2"]/div[1]/div[1]/span[1]'
        for section, team_xpath in zip([bowling1, bowling2], [xpath2, xpath1]):
            team_element = section.find_element(By.XPATH, team_xpath)
            team_words = team_element.text.split(' ')[:-1]
            initials = [word[0] for word in team_words]
            team_name = ''.join(initials)
            
            bowlers = section.find_elements(By.CLASS_NAME, 'cb-scrd-itms')
            for bowler in bowlers:
                name_link = bowler.find_element(By.CLASS_NAME, 'cb-text-link').get_attribute('href')   
                bowler_data['Link'].append(name_link)

                bowler_data['Match Date'].append(date_object.strftime('%Y-%m-%d'))               
                bowler_data['Venue'].append(venue.text)
                bowler_data['Season'].append(season)

                scores = bowler.find_elements(By.CLASS_NAME, 'text-right')
                bowler_data['Overs'].append(scores[0].text)
                bowler_data['Maiden'].append(scores[1].text)
                bowler_data['Runs'].append(scores[2].text)
                bowler_data['Wicket'].append(scores[3].text)
                bowler_data['No Ball'].append(scores[4].text)
                bowler_data['Wide'].append(scores[5].text)
                bowler_data['Economy'].append(scores[6].text)
                bowler_data['Team'].append(team_name)
                
    except NoSuchElementException as e:
        pass

batter_df = pd.DataFrame(batter_data)
bowler_df = pd.DataFrame(bowler_data)


driver.quit()

In [3]:
batter_link = pd.DataFrame({'Link': batter_df['Link'].unique()})
bowler_link = pd.DataFrame({'Link': bowler_df['Link'].unique()})
player_link = pd.concat([batter_link, bowler_link], axis=0).reset_index(drop=True)['Link'].unique()

In [4]:
service = Service(executable_path='/Applications/Chdriver/chromedriver')
driver = webdriver.Chrome(service=service)

player_data = {
    'Link': [],
    'Name': [],
    'Country': [],
    'Born': []
}
for link in player_link:
    driver.get(link)
    time.sleep(0.1)
    
    player_data['Link'].append(link)
    
    name = driver.find_element(By.XPATH, '//*[@id="playerProfile"]/div[1]/div[2]/h1').text
    player_data['Name'].append(name)

    country = driver.find_element(By.XPATH, '//*[@id="playerProfile"]/div[1]/div[2]/h3').text
    player_data['Country'].append(country)

    date_string = driver.find_element(By.XPATH, '//*[@id="playerProfile"]/div[2]/div[1]/div/div[3]').text
    date_part = date_string.split('(')[0].strip()
    parsed_date = datetime.strptime(date_part, '%b %d, %Y')
    formatted_date = parsed_date.strftime('%Y-%m-%d')
    player_data['Born'].append(formatted_date)
    
player_df = pd.DataFrame(player_data)    
driver.quit()

In [5]:
player_df

,Link,Name,Country,Born
0,https://www.cricbuzz.com/profiles/1837/pinal-shah,Pinal Shah,India,1987-11-03
1,https://www.cricbuzz.com/profiles/71/zaheer-khan,Zaheer Khan,India,1978-10-07
2,https://www.cricbuzz.com/profiles/1463/abhishe...,Abhishek Nayar,India,1983-10-08
3,https://www.cricbuzz.com/profiles/75/harbhajan...,Harbhajan Singh,India,1980-07-03
4,https://www.cricbuzz.com/profiles/242/dwayne-b...,Dwayne Bravo,West Indies,1983-10-07
...,...,...,...,...
157,https://www.cricbuzz.com/profiles/732/ranadeb-...,Ranadeb Bose,India,1979-02-27
158,https://www.cricbuzz.com/profiles/1849/abhiman...,Abhimanyu Mithun,India,1989-10-25
159,https://www.cricbuzz.com/profiles/1894/sourav-...,Sourav Sarkar,India,1984-12-15
160,https://www.cricbuzz.com/profiles/215/charl-la...,Charl Langeveldt,South Africa,1974-12-17
161,https://www.cricbuzz.com/profiles/1871/rahil-s...,Rahil Shaikh,India,1985-06-12

In [6]:
df1 = pd.merge(batter_df, player_df, on='Link', how='left')
df2 = pd.merge(bowler_df, player_df, on='Link', how='left')
df1 = df1[['Match Date', 'Name', 'Runs', 'Balls','Fours', 'Sixes', 'Strike Rate', 'Country', 'Born', 'Team', 'Venue', 'Season']]
df2 = df2[['Match Date', 'Name', 'Overs', 'Maiden','Runs', 'Wicket', 'No Ball', 'Wide', 'Economy', 'Country', 'Born', 'Team', 'Venue', 'Season']]

In [7]:
batter_file = 'ipl-2009-batter.csv'
bowler_file = 'ipl-2009-bowler.csv'

df1.to_csv(batter_file, index=False, header=not os.path.isfile(batter_file))
df2.to_csv(bowler_file, index=False, header=not os.path.isfile(bowler_file))

In [8]:
df = pd.read_csv(batter_file)
df

,Match Date,Name,Runs,Balls,Fours,Sixes,Strike Rate,Country,Born,Team,Venue,Season
0,2009-04-18,Pinal Shah,0,0,0,0,0.00,India,1987-11-03,MI,Cape Town,2009
1,2009-04-18,Zaheer Khan,2,3,0,0,66.67,India,1978-10-07,MI,Cape Town,2009
2,2009-04-18,Abhishek Nayar,35,14,2,3,250.00,India,1983-10-08,MI,Cape Town,2009
3,2009-04-18,Harbhajan Singh,4,2,1,0,200.00,India,1980-07-03,MI,Cape Town,2009
4,2009-04-18,Dwayne Bravo,5,4,1,0,125.00,West Indies,1983-10-07,MI,Cape Town,2009
...,...,...,...,...,...,...,...,...,...,...,...,...
806,2009-05-24,Virat Kohli,7,8,1,0,87.50,India,1988-11-05,RCB,Johannesburg,2009
807,2009-05-24,Rahul Dravid,9,13,0,0,69.23,India,1973-01-11,RCB,Johannesburg,2009
808,2009-05-24,Ross Taylor,27,20,3,1,135.00,New Zealand,1984-03-08,RCB,Johannesburg,2009
809,2009-05-24,Roelof van der Merwe,32,21,1,3,152.38,Netherlands,1984-12-31,RCB,Johannesburg,2009
810,2009-05-24,Manish Pandey,4,8,0,0,50.00,India,1989-09-10,RCB,Johannesburg,2009