In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException
import pandas as pd
import time

In [2]:
service = Service(executable_path='/Applications/Chdriver/chromedriver')
driver = webdriver.Chrome(service=service)

url = 'https://www.cricbuzz.com/cricket-series/2330/indian-premier-league-2015/matches'

driver.get(url)

match_urls = []
matches = driver.find_elements(By.CLASS_NAME, 'cb-series-matches')
for match in matches:
    link_element = match.find_element(By.CLASS_NAME, 'text-hvr-underline')
    link = link_element.get_attribute('href')
    link = link.replace("cricket-scores", "live-cricket-scorecard")
    match_urls.append(link)

batter_name = []
batter_team = []
batter_date = []
runs_scored = []
balls_faced = []
fours = []
sixes = []
strike_rate = []

bowler_name = []
bowler_team = []
bowler_date = []
overs = []
maiden = []
runs = []
wicket = []
noball = []
wides = []
economy = []

for match_url in match_urls:
    driver.get(match_url)
    time.sleep(.5)
    try:
        batting1 = driver.find_element(By.XPATH, '//*[@id="innings_1"]/div[1]')
        batters = batting1.find_elements(By.CLASS_NAME, 'cb-scrd-itms')
        for batter in batters[:-3]:
            name = batter.find_element(By.CLASS_NAME, 'cb-text-link')
            batter_name.append(name.text)
            
            team = driver.find_element(By.XPATH, '//*[@id="innings_1"]/div[1]/div[1]/span[1]')
            team_part = team.text.split(' ')[:-1]
            team_name = ' '.join(team_part)
            batter_team.append(team_name)

            date = driver.find_element(By.CSS_SELECTOR, 'span.schedule-date')
            date_object = pd.to_datetime(date.text, format='%A, %B %d, %Y')
            batter_date.append(date_object.strftime('%Y-%m-%d'))

            scores = batter.find_elements(By.CLASS_NAME, 'text-right')
            runs_scored.append(scores[0].text)
            balls_faced.append(scores[1].text)
            fours.append(scores[2].text)
            sixes.append(scores[3].text)
            strike_rate.append(scores[4].text)
            
        batting2 = driver.find_element(By.XPATH, '//*[@id="innings_2"]/div[1]')
        batters = batting2.find_elements(By.CLASS_NAME, 'cb-scrd-itms')
        for batter in batters[:-3]:
            name = batter.find_element(By.CLASS_NAME, 'cb-text-link')
            batter_name.append(name.text)

            team = driver.find_element(By.XPATH, '//*[@id="innings_2"]/div[1]/div[1]/span[1]')
            team_part = team.text.split(' ')[:-1]
            team_name = ' '.join(team_part)
            batter_team.append(team_name)

            date = driver.find_element(By.CSS_SELECTOR, 'span.schedule-date')
            date_object = pd.to_datetime(date.text, format='%A, %B %d, %Y')
            batter_date.append(date_object.strftime('%Y-%m-%d'))

            scores = batter.find_elements(By.CLASS_NAME, 'text-right')
            runs_scored.append(scores[0].text)
            balls_faced.append(scores[1].text)
            fours.append(scores[2].text)
            sixes.append(scores[3].text)
            strike_rate.append(scores[4].text)
            
        bowling1 = driver.find_element(By.XPATH, '//*[@id="innings_1"]/div[4]')
        bowlers = bowling1.find_elements(By.CLASS_NAME, 'cb-scrd-itms')
        for bowler in bowlers:
            name = bowler.find_element(By.CLASS_NAME, 'cb-text-link')
            bowler_name.append(name.text)

            team = driver.find_element(By.XPATH, '//*[@id="innings_2"]/div[1]/div[1]/span[1]')
            team_part = team.text.split(' ')[:-1]
            team_name = ' '.join(team_part)
            bowler_team.append(team_name)

            date = driver.find_element(By.CSS_SELECTOR, 'span.schedule-date')
            date_object = pd.to_datetime(date.text, format='%A, %B %d, %Y')
            bowler_date.append(date_object.strftime('%Y-%m-%d'))

            scores = bowler.find_elements(By.CLASS_NAME, 'text-right')
            overs.append(scores[0].text)
            maiden.append(scores[1].text)
            runs.append(scores[2].text)
            wicket.append(scores[3].text)
            noball.append(scores[4].text)
            wides.append(scores[5].text)
            economy.append(scores[6].text)
            
        bowling2 = driver.find_element(By.XPATH, '//*[@id="innings_2"]/div[4]')
        bowlers = bowling2.find_elements(By.CLASS_NAME, 'cb-scrd-itms')
        for bowler in bowlers:
            name = bowler.find_element(By.CLASS_NAME, 'cb-text-link')
            bowler_name.append(name.text)
            
            team = driver.find_element(By.XPATH, '//*[@id="innings_1"]/div[1]/div[1]/span[1]')
            team_part = team.text.split(' ')[:-1]
            team_name = ' '.join(team_part)
            bowler_team.append(team_name)

            date = driver.find_element(By.CSS_SELECTOR, 'span.schedule-date')
            date_object = pd.to_datetime(date.text, format='%A, %B %d, %Y')
            bowler_date.append(date_object.strftime('%Y-%m-%d'))

            scores = bowler.find_elements(By.CLASS_NAME, 'text-right')
            overs.append(scores[0].text)
            maiden.append(scores[1].text)
            runs.append(scores[2].text)
            wicket.append(scores[3].text)
            noball.append(scores[4].text)
            wides.append(scores[5].text)
            economy.append(scores[6].text)
    
    except NoSuchElementException:
        pass

batter_data = pd.DataFrame({
    'Name': batter_name,
    'Runs': runs_scored,
    'Balls': balls_faced,
    'Fours': fours,
    'Sixes': sixes,
    'Strike Rate': strike_rate,
    'Team': batter_team,
    'Date': batter_date
})

bowler_data = pd.DataFrame({
    'Name': bowler_name,
    'Overs': overs,
    'Maiden': maiden,
    'Runs': runs,
    'Wicket': wicket,
    'No Balls': noball,
    'Wides': wides,
    'Economy': economy,
    'Team': bowler_team,
    'Date': bowler_date
})

batter_data.to_csv('ipl-2015-batter.csv', index=False)
bowler_data.to_csv('ipl-2015-bowler.csv', index=False)

driver.quit()

In [3]:
data = pd.read_csv('ipl-2015-batter.csv')
data

,Name,Runs,Balls,Fours,Sixes,Strike Rate,Team,Date
0,Rohit Sharma,98,65,12,4,150.77,Mumbai Indians,2015-04-08
1,Aaron Finch,5,5,1,0,100.00,Mumbai Indians,2015-04-08
2,Aditya Tare,7,7,1,0,100.00,Mumbai Indians,2015-04-08
3,Ambati Rayudu,0,2,0,0,0.00,Mumbai Indians,2015-04-08
4,Corey Anderson,55,41,4,3,134.15,Mumbai Indians,2015-04-08
...,...,...,...,...,...,...,...,...
877,Pawan Negi,3,5,0,0,60.00,Chennai Super Kings,2015-05-24
878,Faf du Plessis,1,3,0,0,33.33,Chennai Super Kings,2015-05-24
879,Ravindra Jadeja,11,8,1,0,137.50,Chennai Super Kings,2015-05-24
880,Ravichandran Ashwin,2,4,0,0,50.00,Chennai Super Kings,2015-05-24
881,Mohit Sharma,21,7,1,2,300.00,Chennai Super Kings,2015-05-24